name: docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches: 
      - master
    paths:
      - "index.js"
      - "modules"
      - "Dockerfile"
      - ".github/workflows/docker.yml"
  pull_request:
    branches: 
      - master
    paths:
      - "index.js"
      - "modules"
      - "Dockerfile"
      - ".github/workflows/docker.yml"
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      IMAGE_OWNER: annangela

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: false

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry docker.io
        if: github.event.ref_type == 'tag'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: annangela
          password: ${{ secrets.DOCKER_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for annangela/dnspod-ddns
        if: github.event.ref_type == 'tag'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/annangela/dnspod-ddns
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=sha,format=long

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build from Dockerfile and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          sbom: true
